import pg from 'pg';
import fs from 'fs';

async function testLetterNumbering() {
  const client = new pg.Client({ connectionString: 'postgresql://postgres:siloka123%23@127.0.0.1:5432/siloka_db' });
  await client.connect();

  console.log('Applying database/generate_nomor_surat_otomatis.sql...');
  const sql = fs.readFileSync('database/generate_nomor_surat_otomatis.sql', 'utf8');
  await client.query(sql);
  console.log('✓ DDL and Function applied successfully!');

  // Reset counter for UN58.13 in 2026 for clean baseline
  await client.query(`DELETE FROM tbl_counter_surat WHERE kode_unit_kerja IN ('UN58.13', 'UN58.6', 'UN58') AND tahun = 2026;`);

  // Test 1: Direct function call for FT (UN58.13)
  console.log('\n--- Test 1: Direct function execution for FT (UN58.13) ---');
  const res1 = await client.query("SELECT generate_nomor_surat_otomatis('UN58.13', 'PP.00.03', '2026-09-22') AS nomor_surat");
  console.log('Nomor Surat 1 (harus 0001):', res1.rows[0].nomor_surat);

  const res2 = await client.query("SELECT generate_nomor_surat_otomatis('UN58.13', 'PP.00.03', '2026-09-22') AS nomor_surat");
  console.log('Nomor Surat 2 (harus 0002):', res2.rows[0].nomor_surat);

  // Test 2: Direct function call for BKU (UN58.6)
  console.log('\n--- Test 2: Direct function execution for BKU (UN58.6) ---');
  const res3 = await client.query("SELECT generate_nomor_surat_otomatis('UN58.6', 'KU.01.04', '2026-09-22') AS nomor_surat");
  console.log('Nomor Surat BKU (harus 0001):', res3.rows[0].nomor_surat);

  // Test 3: Resolution via user_id
  console.log('\n--- Test 3: Dynamic resolution via user_id (usr-01 / Rektorat) ---');
  const resUser = await client.query("SELECT generate_nomor_surat_otomatis('usr-01', 'PP.00.01', '2026-09-22') AS nomor_surat");
  console.log('Nomor Surat via user_id usr-01 (unit UN58):', resUser.rows[0].nomor_surat);

  // Test 4: Trigger-based insertion into tbl_surat
  console.log('\n--- Test 4: Trigger-based insertion into tbl_surat with nomor_surat = NULL ---');
  const insRes = await client.query(`
    INSERT INTO tbl_surat (tanggal_surat, perihal, jenis_surat, kode_jra, kode_unit_kerja, status_progres)
    VALUES ('2026-09-22', 'Pengumuman Pelaksanaan Ujian Mandiri Gelombang 2', 'Surat Keluar', 'PP.00.03', 'UN58.13', 'Disetujui')
    RETURNING id_surat, nomor_surat, kode_unit_kerja, tanggal_surat;
  `);
  console.table(insRes.rows);
  console.log('Generated by Trigger (harus 0003):', insRes.rows[0].nomor_surat);

  // Test 5: Simulated year rollover (Tahun 2027)
  console.log('\n--- Test 5: Simulated year rollover (Tahun 2027 reset to 0001) ---');
  const resRollover = await client.query("SELECT generate_nomor_surat_otomatis('UN58.13', 'PP.00.03', '2027-01-02') AS nomor_surat");
  console.log('Nomor Surat Tahun 2027 (harus reset ke 0001):', resRollover.rows[0].nomor_surat);

  // Test 6: Check counter table content
  console.log('\n--- Test 6: Counter table contents ---');
  const counters = await client.query('SELECT * FROM tbl_counter_surat ORDER BY tahun, kode_unit_kerja');
  console.table(counters.rows);

  // Test 7: Concurrency Simulation (10 concurrent requests simultaneously)
  console.log('\n--- Test 7: Concurrency Simulation (10 simultaneous concurrent calls) ---');
  const promises = [];
  for (let i = 0; i < 10; i++) {
    promises.push(
      (async () => {
        const subClient = new pg.Client({ connectionString: 'postgresql://postgres:siloka123%23@127.0.0.1:5432/siloka_db' });
        await subClient.connect();
        const r = await subClient.query("SELECT generate_nomor_surat_otomatis('UN58.13', 'PP.00.03', '2026-09-22') AS nomor_surat");
        await subClient.end();
        return r.rows[0].nomor_surat;
      })()
    );
  }
  const concurrentResults = await Promise.all(promises);
  console.log('10 Concurrent Numbers:', concurrentResults);
  const uniqueSet = new Set(concurrentResults);
  console.log(`Unique numbers count: ${uniqueSet.size} of 10. Any duplicates? ${uniqueSet.size === 10 ? 'NO DUPLICATES! (Safe)' : 'DUPLICATE DETECTED!'}`);

  await client.end();
}

testLetterNumbering().catch(err => {
  console.error('Fatal Error:', err);
  process.exit(1);
});

